apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetdb
spec:
  selector:
    matchLabels:
      app: fleetdb
  replicas: 1
  template: # template for the webapp
    metadata:
      labels:
        app: fleetdb
    spec:
      containers:
      - name: fleetdb
        image: docker.io/chazpogz/orekadb:v2
