apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  ports:
    - name: http
      port: 80
      nodePort: 30080

  selector:
    app: webapp

  type: NodePort

---

kind: Service
apiVersion: v1
metadata:
  name: fleetman-queue
spec:
  ports:
    - name: http
      port: 8161
      nodePort: 30010

    - name: endpoint
      port: 61616
      
  selector:
    app: queue

  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  ports:
    - name: http
      port: 8080

  selector:
    app: position-tracker

  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-api-gateway
spec:
  ports:
    - name: http
      port: 8080
      
  selector:
    app: position-api-gateway

  type: ClusterIP

