apiVersion: v1
kind: Service
metadata:
  name: orkweb
spec:
  ports:
    - name: http
      port: 8080
      nodePort: 30080

  selector:
    app: orkweb

  type: NodePort

---

kind: Service
apiVersion: v1
metadata:
  name: fleetdb
spec:
  ports:
    - name: orekadbport
      port: 3306

  selector:
      app: fleetdb

  type: ClusterIP

